table Settings
	lineageTag: d2ed4c2d-3270-4473-ae92-03e383c654b5

	/// For use in slicers and other visuals to limit dimensions where a value exists for the dimension member. Can be used to create cascading slicers.
	measure 'Investment Metric Exists' = INT(NOT(ISEMPTY('Investment Metrics')))
		formatString: 0
		displayFolder: Filters & Misc
		lineageTag: 62a93394-965a-4129-8d1e-da09932bd19f

	measure PulseInfoIconHTML = ```
			
			"
			<style>
			@keyframes pulse {
			  0%   { transform: scale(1);   }
			  50%  { transform: scale(1.22); }
			  100% { transform: scale(1);   }
			}
			.pulse {
			  width: 40px; height: 40px; 
			  display:inline-block;
			  animation: pulse 0.6s ease-in-out 3; /* 3 pulses */
			  transform-origin: center;
			}
			</style>
			<svg class='pulse' viewBox='0 0 640 640'><!--!Font Awesome Free 7.0.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path fill='#1f3f5b' d='M320 576C461.4 576 576 461.4 576 320C576 178.6 461.4 64 320 64C178.6 64 64 178.6 64 320C64 461.4 178.6 576 320 576zM288 224C288 206.3 302.3 192 320 192C337.7 192 352 206.3 352 224C352 241.7 337.7 256 320 256C302.3 256 288 241.7 288 224zM280 288L328 288C341.3 288 352 298.7 352 312L352 400L360 400C373.3 400 384 410.7 384 424C384 437.3 373.3 448 360 448L280 448C266.7 448 256 437.3 256 424C256 410.7 266.7 400 280 400L304 400L304 336L280 336C266.7 336 256 325.3 256 312C256 298.7 266.7 288 280 288z'/></svg>"
			//<!-- Use an inline SVG circle as the icon (swap to your SVG/path or <img src> logo) -->
			//<svg class='pulse' viewBox='0 0 24 24' aria-label='attention'>
			//  <circle cx='12' cy='12' r='10' fill='#ffb300'/>
			//</svg>
			//"
			
			```
		isHidden
		displayFolder: Filters & Misc
		lineageTag: 5ff2c775-b90c-473c-9d08-4b767dd460ac

		changedProperty = IsHidden

	measure PulseSlicerIconHTML = ```
			
			"
			<style>
			@keyframes pulse {
			  0%   { transform: scale(1);   }
			  50%  { transform: scale(1.22); }
			  100% { transform: scale(1);   }
			}
			.pulse {
			  width: 40px; height: 40px; 
			  display:inline-block;
			  animation: pulse 0.6s ease-in-out 3; /* 3 pulses */
			  transform-origin: center;
			}
			</style>
			<svg class='pulse' viewBox='0 0 640 640'><!--!Font Awesome Free 7.0.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path fill='#1f3f5b' d='M96 128C78.3 128 64 142.3 64 160C64 177.7 78.3 192 96 192L182.7 192C195 220.3 223.2 240 256 240C288.8 240 317 220.3 329.3 192L544 192C561.7 192 576 177.7 576 160C576 142.3 561.7 128 544 128L329.3 128C317 99.7 288.8 80 256 80C223.2 80 195 99.7 182.7 128L96 128zM96 288C78.3 288 64 302.3 64 320C64 337.7 78.3 352 96 352L342.7 352C355 380.3 383.2 400 416 400C448.8 400 477 380.3 489.3 352L544 352C561.7 352 576 337.7 576 320C576 302.3 561.7 288 544 288L489.3 288C477 259.7 448.8 240 416 240C383.2 240 355 259.7 342.7 288L96 288zM96 448C78.3 448 64 462.3 64 480C64 497.7 78.3 512 96 512L150.7 512C163 540.3 191.2 560 224 560C256.8 560 285 540.3 297.3 512L544 512C561.7 512 576 497.7 576 480C576 462.3 561.7 448 544 448L297.3 448C285 419.7 256.8 400 224 400C191.2 400 163 419.7 150.7 448L96 448z'/></svg>"
			
			```
		isHidden
		displayFolder: Filters & Misc
		lineageTag: 9dbeb730-a44c-40b4-8989-ebdf696c08b6

		changedProperty = IsHidden

	measure PulseGearsHTML = ```
			
			"
			<style>
			@keyframes pulse {
			  0%   { transform: scale(1);   }
			  50%  { transform: scale(1.22); }
			  100% { transform: scale(1);   }
			}
			.pulse {
			  width: 40px; height: 40px; 
			  display:inline-block;
			  animation: pulse 0.6s ease-in-out 3; /* 3 pulses */
			  transform-origin: center;
			}
			</style>
			<svg class='pulse' viewBox='0 0 640 640'><!--!Font Awesome Free 7.0.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path fill='#1f3f5b' d='M415.9 274.5C428.1 271.2 440.9 277 446.4 288.3L465 325.9C475.3 327.3 485.4 330.1 494.9 334L529.9 310.7C540.4 303.7 554.3 305.1 563.2 314L582.4 333.2C591.3 342.1 592.7 356.1 585.7 366.5L562.4 401.4C564.3 406.1 566 411 567.4 416.1C568.8 421.2 569.7 426.2 570.4 431.3L608.1 449.9C619.4 455.5 625.2 468.3 621.9 480.4L614.9 506.6C611.6 518.7 600.3 526.9 587.7 526.1L545.7 523.4C539.4 531.5 532.1 539 523.8 545.4L526.5 587.3C527.3 599.9 519.1 611.3 507 614.5L480.8 621.5C468.6 624.8 455.9 619 450.3 607.7L431.7 570.1C421.4 568.7 411.3 565.9 401.8 562L366.8 585.3C356.3 592.3 342.4 590.9 333.5 582L314.3 562.8C305.4 553.9 304 540 311 529.5L334.3 494.5C332.4 489.8 330.7 484.9 329.3 479.8C327.9 474.7 327 469.6 326.3 464.6L288.6 446C277.3 440.4 271.6 427.6 274.8 415.5L281.8 389.3C285.1 377.2 296.4 369 309 369.8L350.9 372.5C357.2 364.4 364.5 356.9 372.8 350.5L370.1 308.7C369.3 296.1 377.5 284.7 389.6 281.5L415.8 274.5zM448.4 404C424.1 404 404.4 423.7 404.5 448.1C404.5 472.4 424.2 492 448.5 492C472.8 492 492.5 472.3 492.5 448C492.4 423.6 472.7 404 448.4 404zM224.9 18.5L251.1 25.5C263.2 28.8 271.4 40.2 270.6 52.7L267.9 94.5C276.2 100.9 283.5 108.3 289.8 116.5L331.8 113.8C344.3 113 355.7 121.2 359 133.3L366 159.5C369.2 171.6 363.5 184.4 352.2 190L314.5 208.6C313.8 213.7 312.8 218.8 311.5 223.8C310.2 228.8 308.4 233.8 306.5 238.5L329.8 273.5C336.8 284 335.4 297.9 326.5 306.8L307.3 326C298.4 334.9 284.5 336.3 274 329.3L239 306C229.5 309.9 219.4 312.7 209.1 314.1L190.5 351.7C184.9 363 172.1 368.7 160 365.5L133.8 358.5C121.6 355.2 113.5 343.8 114.3 331.3L117 289.4C108.7 283 101.4 275.6 95.1 267.4L53.1 270.1C40.6 270.9 29.2 262.7 25.9 250.6L18.9 224.4C15.7 212.3 21.4 199.5 32.7 193.9L70.4 175.3C71.1 170.2 72.1 165.2 73.4 160.1C74.8 155 76.4 150.1 78.4 145.4L55.1 110.5C48.1 100 49.5 86.1 58.4 77.2L77.6 58C86.5 49.1 100.4 47.7 110.9 54.7L145.9 78C155.4 74.1 165.5 71.3 175.8 69.9L194.4 32.3C200 21 212.7 15.3 224.9 18.5zM192.4 148C168.1 148 148.4 167.7 148.4 192C148.4 216.3 168.1 236 192.4 236C216.7 236 236.4 216.3 236.4 192C236.4 167.7 216.7 148 192.4 148z'/></svg>"
			```
		isHidden
		displayFolder: Filters & Misc
		lineageTag: 73e4c50e-5c8e-4a9e-99c8-e320253dbfa5

		changedProperty = IsHidden

	/// For use in slicers and other visuals to limit dimensions where a transaction exists for the dimension member. Can be used to create cascading slicers.
	measure 'Transaction Exists' = INT(NOT(ISEMPTY('Transactions')))
		formatString: 0
		displayFolder: Filters & Misc
		lineageTag: e6f2bd3f-ae25-4d71-a7e8-981f485c3e04

	/// The URL linked to the logo on each page.
	column WebURL
		dataType: string
		lineageTag: 1f69219c-6186-4fd3-b1be-a6c9a00c4a43
		summarizeBy: none
		sourceColumn: WebURL

		annotation SummarizationSetBy = Automatic

	/// The company name used as the tooltip for the logo on each page.
	column 'Company Name'
		dataType: string
		lineageTag: 5d52e3ce-87fa-4eb8-a74b-d58a4ec16212
		summarizeBy: none
		sourceColumn: Company Name

		annotation SummarizationSetBy = Automatic

	partition Settings = m
		mode: import
		queryGroup: 'Model tables'
		source =
				let
				    Source = Excel.Workbook(Web.Contents(ExcelFileURL), null, true),
				    Valuations_Table = Source{[Item="Settings",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Valuations_Table,{{"WebURL", type text}, {"Company Name", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

